CREATE DATABASE IF NOT EXISTS anime_db;
USE anime_db;

DROP TABLE IF EXISTS actors;

CREATE TABLE actors (
    actors_id INT NOT NULL AUTO_INCREMENT,
    last_name VARCHAR(50),
    first_name VARCHAR(50),
    gender VARCHAR(10),
    date_of_birth DATE,
    place_of_birth VARCHAR(100),
    agency VARCHAR(100),
    PRIMARY KEY (actors_id)
);

INSERT INTO actors (last_name, first_name, gender, date_of_birth, place_of_birth, agency)
VALUES

('Han', 'Megumi', 'Female', '1989-06-03', 'Tokyo, Japan', 'Atomic Monkey'),
('Ise', 'Mariya', 'Female', '1988-09-25', 'Kanagawa, Japan', 'Across Entertainment'),
('Sawashiro', 'Miyuki', 'Female', '1985-06-02', 'Nagano, Japan', 'Aoni Production'),
('Fujiwara', 'Keiji', 'Male', '1964-10-05', 'Tokyo, Japan', 'Air Agency'),
('Namikawa', 'Daisuke', 'Male', '1976-04-02', 'Tokyo, Japan', 'Stay Luck'),
('Koyama', 'Rikiya', 'Male', '1963-12-18', 'Kyoto, Japan', 'Haiyuza Theatre Company'),
('Ueda', 'Youji', 'Male', '1971-08-07', 'Kobe, Hyogo, Japan', 'Atomic Monkey'),
(NULL, 'Mugihito', 'Male', '1944-08-08', 'Tokyo, Japan', 'Office Osawa'),
('Tanaka', 'Atsuko', 'Female', '1962-11-14', 'Maebashi, Gunma, Japan', 'Mausu Promotion'),
('Suwabe', 'Junichi', 'Male', '1972-03-29', 'Tokyo, Japan', 'Haine'),
('Matsumoto', 'Yasunori', 'Male', '1960-02-07', 'Yamanashi, Japan', 'Office Osawa'),
('Minaguchi', 'Yuko', 'Female', '1966-06-26', 'Bunkyo, Tokyo, Japan', 'Aoni Production'),
('Mitsuishi', 'Kotono', 'Female', '1967-12-08', 'Tokyo, Japan', 'Arts Vision'),
('Okitsu', 'Kazuyuki', 'Male', '1980-03-08', 'Kanagawa, Japan', 'Ken Production'),
('Konishi', 'Katsuyuki', 'Male', '1973-04-21', 'Wakayama, Japan', 'Ken Production'),
('Kuwashima', 'Houko', 'Female', '1975-12-12', 'Kanagawa, Japan', 'Office Osawa'),
('Suzuki', 'Kappei', 'Male', '1965-11-25', 'Kushiro, Hokkaido, Japan', '81 Produce'),
('Ishida', 'Akira', 'Male', '1967-11-02', 'Aichi, Japan', 'Peerless Gerbera'),
('Terashima', 'Takuma', 'Male', '1983-12-20', 'Ishikawa, Japan', 'Axl One'),
('Nakata', 'Jouji', 'Male', '1954-04-22', 'Tokyo, Japan', 'Haikyō'),
('Paku', 'Romi', 'Female', '1972-01-22', 'Edo, Tokyo, Japan', 'Atomic Monkey'),
('Miyano', 'Mamoru', 'Male', '1983-06-08', 'Saitama Prefecture, Japan', 'Ken-On'),
('Yamaguchi', 'Kappei', 'Male', '1965-05-23', 'Fukuoka, Japan', 'Gokū & 21st Century Fox'),
('Hirano', 'Aya', 'Female', '1987-10-08', 'Nagoya, Aichi Prefecture, Japan', 'Independent'),
('Nakamura', 'Shidou', 'Male', '1972-09-14', 'Tokyo, Japan', 'Shido Nakamura Office'),
('Hidaka', 'Noriko', 'Female', '1962-05-31', 'Chiyoda, Tokyo, Japan', 'Big Mount'),
('Saitō', 'Kimiko', 'Female', '1977-02-12', 'Nagano Prefecture, Japan', 'Aoni Production'),
('Sasaki', 'Nozomu', 'Male', '1967-01-25', 'Japan', 'Aoni Production'),
('Uchida', 'Naoya', 'Male', '1953-05-01', 'Japan', 'Office Osawa'),
('Watanabe', 'Akeno', 'Female', '1982-11-18', 'Funabashi, Chiba Prefecture, Japan', 'Office Osawa'),
('Kuwashima', 'Hōko', 'Female', '1975-12-12', 'Kanagawa Prefecture, Japan', 'Office Osawa'),
('Furukawa', 'Makoto', 'Male', '1989-09-29', 'Kumamoto Prefecture, Japan', 'Toy’s Factory'),
('Ishikawa', 'Kaito', 'Male', '1993-10-13', 'Bunkyō, Tokyo, Japan', 'Stay Luck'),
('Kaji', 'Yūki', 'Male', '1985-09-03', 'Tokyo, Japan', 'VIMS'),
('Hayami', 'Saori', 'Female', '1991-05-29', 'Tokyo, Japan', 'I''m Enterprise'),
('Hanae', 'Natsuki', 'Male', '1991-06-26', 'Kanagawa Prefecture, Japan', 'Across Entertainment'),
('Kitō', 'Akari', 'Female', '1994-10-16', 'Nagoya, Aichi Prefecture, Japan', 'Raccoon Dog'),
('Shimono', 'Hiro', 'Male', '1980-04-21', 'Tokyo, Japan', 'I''m Enterprise'),
('Matsuoka', 'Yoshitsugu', 'Male', '1985-09-17', 'Chiba Prefecture, Japan', 'I''m Enterprise'),
('Suzumura', 'Kenichi', 'Male', '1975-03-12', 'Nagano Prefecture, Japan', 'Aoni Production'),
('Sakamoto', 'Maaya', 'Female', '1980-03-31', 'Tokyo, Japan', 'Flying Dog'),
('Matsukaze', 'Masaya', 'Male', '1976-09-09', 'Fukushima Prefecture, Japan', 'Aoni Production'),
('Fujita', 'Yoshinori', 'Male', '1976-10-27', 'Aomori, Japan', 'Arts Vision'),
('Saitō', 'Ayaka (voice actor for Honey)', 'Female', '1988-06-02', 'Tokyo, Japan', 'Aoni Production'),
('Kirii', 'Daisuke', 'Male', '1975-07-23', 'Japan', 'Office Osawa'),
('Koyasu', 'Takehito', 'Male', '1967-05-05', 'Yokohama, Kanagawa Prefecture, Japan', 'T''s Factory'),
('Ono', 'Daisuke', 'Male', '1978-05-04', 'Sakawa, Kōchi Prefecture, Japan', 'Freelance'),
('Nakamura', 'Yūichi', 'Male', '1980-02-20', 'Aji, Kagawa Prefecture, Japan', 'INTENTION'),
('Sugita', 'Tomokazu', 'Male', '1980-10-11', 'Saitama Prefecture, Japan', 'AGRS'),
('Ishizuka', 'Unshō', 'Male', '1951-05-16', 'Katsuyama, Fukui Prefecture, Japan', 'Aoni Production'),
('Murase', 'Ayumu', 'Male', '1988-12-14', 'United States (raised in Aichi Prefecture, Japan)', 'Aster Nine'),
('Irino', 'Miyu', 'Male', '1988-02-19', 'Tokyo, Japan', 'Junction Agency'),
('Hosoya', 'Yoshimasa', 'Male', '1982-02-10', 'Onomichi, Hiroshima, Japan', 'Mausu Promotion'),
('Okamoto', 'Nobuhiko', 'Male', '1986-10-24', 'Tokyo, Japan', 'Raccoon Dog'),
('Hayashi', 'Yū', 'Male', '1983-04-02', 'Zama, Kanagawa, Japan', 'Ken Production'),
('Uchiyama', 'Koki', 'Male', '1990-08-16', 'Saitama Prefecture, Japan', 'Himawari Theatre Group'),
('Saitō', 'Sōma', 'Male', '1991-04-22', 'Yamanashi, Japan', '81 Produce'),
('Yamashita', 'Daiki', 'Male', '1989-09-07', 'Hamamatsu, Shizuoka Prefecture, Japan', 'Arts Vision'),
('Sakura', 'Ayane', 'Female', '1994-01-29', 'Shibuya, Tokyo, Japan', 'Aoni Production'),
('Eguchi', 'Takuya', 'Male', '1987-05-22', 'Setagaya, Tokyo, Japan', '81 Produce'),
('Tanezaki', 'Atsumi', 'Female', '1990-09-27', 'Ōita Prefecture, Japan', 'Tokyo Actor''s Consumer''s Cooperative Society / Haikyo'),
('Matsuda', 'Kenichiro', 'Male', '1978-09-22', 'Saitama Prefecture, Japan', 'Arts Vision'),
('Ono', 'Kenshō', 'Male', '1989-10-05', 'Fukuoka, Fukuoka Prefecture, Japan', 'Animo Produce'),
('Takeuchi', 'Junko', 'Female', '1972-04-05', 'Saitama Prefecture, Japan', 'Ogipro The Next / Amuse'),
('Sugiyama', 'Noriaki', 'Male', '1974-03-09', 'Tokyo, Japan', 'Stay-Luck'),
('Nakamura', 'Chie', 'Female', '1978-05-14', 'Tokyo, Japan', 'Axlone'),
('Inoue', 'Kazuhiko', 'Male', '1954-03-26', 'Yokohama, Kanagawa Prefecture, Japan', 'B-Box'),
('Morikubo', 'Showtaro', 'Male', '1974-02-25', 'Hachioji, Tokyo, Japan', 'VIMS'),
('Kosugi', 'Jurota', 'Male', '1957-12-29', 'Yokohama, Kanagawa Prefecture, Japan', 'Haikyō'),
('Kazama', 'Toriumi', 'Male', '1973-05-16', 'Kanagawa Prefecture, Japan', 'Arts Vision'),
('Shimamoto', 'Miyuki', 'Female', '1958-11-05', 'Kumamoto Prefecture, Japan', 'Aoni Production'),
('Miki', 'Shinichiro', 'Male', '1968-03-18', 'Tokyo, Japan', '81 Produce'),
('Tanaka', 'Mayumi', 'Female', '1955-01-15', 'Tokyo, Japan', 'Aoni Production'),
('Nakai', 'Kazuya', 'Male', '1967-11-25', 'Kobe, Hyōgo Prefecture, Japan', 'Aoni Production'),
('Okamura', 'Akemi', 'Female', '1969-03-12', 'Tokyo, Japan', 'Mausu Promotion'),
('Hirata', 'Hiroaki', 'Male', '1963-12-06', 'Tokyo, Japan', 'Hirata Production'),
('Ōtani', 'Ikue', 'Female', '1965-08-18', 'Tokyo, Japan', 'Mausu Promotion'),
('Yamaguchi', 'Yuriko', 'Female', '1965-11-21', 'Japan', 'Aoni Production'),
('Morita', 'Masakazu', 'Male', '1972-10-21', 'Tokyo, Japan', 'Aoni Production'),
('Orikasa', 'Fumiko', 'Female', '1974-12-27', 'Edo (now Tokyo), Japan', 'Atomic Monkey'),
('Matsuoka', 'Yuki', 'Male', '1970-09-13', 'Hirakata, Osaka Prefecture, Japan', 'Aoni Production'),
('Itou', 'Shunsuke', 'Male', '1977-03-20', 'Tokyo, Japan', 'Ken Production'),
('Nakamura', 'Yuuichi', 'Male', '1980-02-20', 'Aji, Kagawa Prefecture, Japan', 'INTENTION'),
('Yukino', 'Satsuki', 'Female', '1970-05-25', 'Chiba Prefecture, Japan', 'Aoni Production'),
('Sugou', 'Toru', 'Male', '1971-04-28', 'Chiba Prefecture, Japan', 'Ken Production'),
('Orikasa', 'Ai', 'Female', '1973-12-12', 'Tokyo, Japan', 'Aoni Production'),
('Hayami', 'Shou', 'Male', '1958-08-02', 'Tokyo, Japan', 'Production Baobab'),
('Yasumoto', 'Hiroki', 'Male', '1977-03-16', 'Yamaguchi Prefecture, Japan', 'Aoni Production'),
('Asano', 'Masaya', 'Male', '1978-04-25', 'Tokyo, Japan', 'Office Osawa'),
('Ichikawa', 'Aoi', 'Male', '1991-10-02', 'Fukuoka, Japan', 'Office Osawa'),
('Hanamori', 'Yumiri', 'Female', '1997-08-29', 'Saitama Prefecture, Japan', 'Aster Nine'),
('Morikawa', 'Toshiyuki', 'Male', '1967-05-26', 'Toyama Prefecture, Japan', 'Axlone'),
('Shin', 'Yuuki', 'Male', '1998-02-22', 'Kanagawa, Japan', 'Ken Production'),
('Nakao', 'Ryūsei', 'Male', '1951-04-02', 'Katsuyama, Fukui Prefecture, Japan', 'Aoni Production'),
('Hanazawa', 'Kana', 'Female', '1989-02-25', 'Tokyo, Japan', 'Office Osawa'),
('Ura', 'Kazuki', 'Male', '1995-10-18', 'Hyōgo Prefecture, Japan', 'VIMS'),
('Kamiya', 'Hiroshi', 'Male', '1975-01-28', 'Yokohama, Kanagawa Prefecture, Japan', 'Aoni Production'),
('Nishiyama', 'Kōtarō', 'Male', '1989-06-07', 'Niigata Prefecture, Japan', 'Aoni Production'),
('Iwami', 'Manaka', 'Female', '1998-11-30', 'Hiroshima Prefecture, Japan', 'Raccoon Dog'),
('Sakata', 'Shōgo', 'Male', '1997-07-07', 'Tokyo, Japan', 'Haikyō'),
('Miura', 'Kaito', 'Male', '2000-03-08', 'Kanagawa Prefecture, Japan', '81 Produce'),
(NULL, 'Aimi', 'Female', '1993-05-13', 'Kishiwada, Osaka Prefecture, Japan', '81 Produce'),
('Kimura', 'Ryōhei', 'Male', '1985-06-29', 'Fukuoka Prefecture, Japan', 'Aoni Production'),
('Kishio', 'Daisuke', 'Male', '1974-08-11', 'Yokohama, Kanagawa Prefecture, Japan', 'Haikyō'),
('Koyama', 'Tsuyoshi', 'Male', '1959-12-11', 'Minato, Tokyo, Japan', 'Aoni Production'),
('Masutani', 'Yasunori', 'Male', '1964-08-19', 'Hamamatsu, Shizuoka Prefecture, Japan', '81 Produce'),
('Ogata', 'Megumi', 'Female', '1965-06-03', 'Kita, Tokyo, Japan', 'Aoni Production'),
('Enoki', 'Junya', 'Male', '1988-10-19', 'Tokyo, Japan', 'Atomic Monkey'),
('Uchida', 'Yuma', 'Male', '1992-09-21', 'Osaka Prefecture, Japan', 'INTENTION'),
('Seto', 'Asami', 'Female', '1985-12-02', 'Saitama Prefecture, Japan', 'StarCrew'),
('Kajita', 'Takahiro', 'Male', '1993-09-28', 'Fukuoka Prefecture, Japan', 'Haikyō'),
('Sakurai', 'Takahiro', 'Male', '1974-06-13', 'Aichi Prefecture, Japan', 'INTENTION'),
('Hara', 'Yumi', 'Female', '1985-01-21', 'Gifu Prefecture, Japan', 'Arts Vision'),
('Komatsu', 'Mikako', 'Female', '1988-11-11', 'Tokushima Prefecture, Japan', 'Hirata Office'),
('Nakamura', 'Kaito', 'Male', '1984-11-25', 'Aichi Prefecture, Japan', 'Aoni Production'),
('Hayashibara', 'Megumi', 'Female', '1967-03-30', 'Tokyo, Japan', 'Woodpark Office'),
('Kobayashi', 'Chiaki', 'Female', '1986-06-04', 'Tokyo, Japan', 'Office Osawa'),
('Hanagaki', 'Yuki', 'Male', '1986-03-06', 'Aichi Prefecture, Japan', 'Atomic Monkey'),
('Hayashi', 'Yoshitsugu', 'Male', '1985-09-17', 'Chiba Prefecture, Japan', 'I''m Enterprise'),
('Kawanishi', 'Kengo', 'Male', '1985-02-18', 'Osaka Prefecture, Japan', 'Mausu Promotion'),
('Karino', 'Shun', 'Male', '1988-01-20', 'Aichi Prefecture, Japan', 'Air Agency'),
('Tachibana', 'Azumi', 'Female', '1994-04-27', 'Kanagawa Prefecture, Japan', 'Arts Vision'),
('Nojima', 'Kentarou', 'Male', '1983-03-18', 'Tokyo, Japan', 'Amuleto'),
('Tamura', 'Mutsumi', 'Female', '1987-06-19', 'Aomori Prefecture, Japan', 'I’m Enterprise'),
('Toyonaga', 'Toshiyuki', 'Male', '1984-04-28', 'Tokyo, Japan', 'Stardust Promotion'),
('Nishiyama', 'Koutarou', 'Male', '1989-06-07', 'Niigata Prefecture, Japan', 'Arts Vision'),
('Toki', 'Shunichi', 'Male', '1989-10-20', 'Hyōgo Prefecture, Japan', 'Atomic Monkey'),
('Hayashi', 'Yūsuke', 'Male', '1980-12-17', 'Tokyo, Japan', 'Haikyō'),
('Kimura', 'Ryouhei', 'Male', '1985-07-30', 'Tokyo, Japan', 'Aoni Production'),
('Nojima', 'Kensho', 'Male', '1986-03-16', 'Tokyo, Japan', 'Stardust Promotion'),
('Shingaki', 'Tarou', 'Male', '1972-01-18', 'Hokkaido, Japan', 'Aoni Production'),
('Fukuyama', 'Jun', 'Male', '1978-11-26', 'Fukushima Prefecture, Japan', 'Axl One'),
('Nozawa', 'Masako', 'Female', '1936-10-25', 'Arakawa, Tokyo, Japan', 'Aoni Production'),
('Horikawa', 'Ryo', 'Male', '1958-02-01', 'Osaka, Japan', 'Aoni Production'),
('Furukawa', 'Toshio', 'Male', '1946-07-16', 'Ōita Prefecture, Japan', 'Aoni Production'),
('Takayama', 'Minami', 'Female', '1964-05-05', 'Tokyo, Japan', 'Two-Top'),
('Mitsuya', 'Yuuji', 'Male', '1954-10-04', 'Tokyo, Japan', '81 Produce'),
('Watanabe', 'Naoko', 'Female', '1959-11-21', 'Niigata Prefecture, Japan', 'Aoni Production'),
('Gouri', 'Daisuke', 'Male', '1952-02-08', 'Hyogo Prefecture, Japan', 'Aoni Production'),
('Hirotaka', 'Suzuoki', 'Male', '1950-03-06', 'Nagoya, Japan', 'Seinenza'),
('Midorikawa', 'Hikaru', 'Male', '1968-05-02', 'Tokyo, Japan', 'Aoni Production'),
('Tachiki', 'Fumihiko', 'Male', '1961-04-29', 'Nagasaki, Japan', 'Haikyō'),
('Wakamoto', 'Norio', 'Male', '1945-10-18', 'Yamaguchi Prefecture, Japan', 'Aoni Production'),
('Nakano', 'Kōhei', 'Male', '1960-12-24', 'Tokyo, Japan', 'Aoni Production'),
('Nakano', 'Ryūsei', 'Male', '1951-03-05', 'Fukui Prefecture, Japan', 'Aoni Production'),
('Mizushima', 'Yuko', 'Female', '1958-05-11', 'Tokyo, Japan', '81 Produce'),
('Kusao', 'Takeshi', 'Male', '1965-11-20', 'Saitama Prefecture, Japan', 'Aoni Production'),
('Furuta', 'Kenji', 'Male', '1956-03-20', 'Kanagawa Prefecture, Japan', 'Aoni Production'),
('Aoi', 'Yūki', 'Female', '1992-03-27', 'Chiba Prefecture, Japan', 'Aoni Production'),
('Ono', 'Tomokazu', 'Male', '1977-05-16', 'Sanmu, Chiba Prefecture, Japan', 'Mausu Promotion'),
('Fairouz', 'Ai', 'Female', '1993-07-06', 'Tokyo, Japan', 'Raccoon Dog'),
('Komatsu', 'Mikako', 'Female', '1988-11-11', 'Tokushima Prefecture, Japan', 'Hirata Office'),
('Fujii', 'Yui', 'Female', '1990-06-11', 'Kanagawa Prefecture, Japan', 'Aoni Production'),
('Takeuchi', 'Shunsuke', 'Male', '1976-09-12', 'Tokyo, Japan', '81 Produce'),
('Ueda', 'Reina', 'Female', '1994-01-17', 'Toyama Prefecture, Japan', '81 Produce'),
('Hikasa', 'Yoko', 'Female', '1985-07-16', 'Kanagawa Prefecture, Japan', 'I''m Enterprise'),
('Toyama', 'Nao', 'Female', '1992-03-11', 'Tokyo, Japan', 'Office Osawa'),
('Koga', 'Aoi', 'Female', '1998-08-24', 'Saga Prefecture, Japan', '81 Produce'),
('Kohara', 'Konomi', 'Female', '1992-06-28', 'Chiba Prefecture, Japan', 'Office Osawa'),
('Suzuki', 'Ryota', 'Male', '1998-03-29', 'Aichi Prefecture, Japan', 'INTENTION'),
('Tomita', 'Miyu', 'Female', '1999-11-15', 'Saitama Prefecture, Japan', 'Amuse'),
('Yamamoto', 'Shou', 'Male', '1983-11-07', 'Fukuoka Prefecture, Japan', 'Aoni Production'),
('Toyosaki', 'Aki', 'Female', '1986-10-28', 'Tokushima Prefecture, Japan', 'Music Ray’n'),
('Satou', 'Rina', 'Female', '1981-05-02', 'Fukuoka Prefecture, Japan', 'Aoni Production'),
('Ishikawa', 'Yui', 'Female', '1989-05-30', 'Aichi Prefecture, Japan', 'Sigma Seven'),
('Hayami', 'Shinichiro', 'Male', '1970-07-14', 'Hiroshima Prefecture, Japan', 'Office Osawa'),
('Endou', 'Aya', 'Female', '1980-02-17', 'Aomori Prefecture, Japan', 'Office Osawa'),
('Kakuma', 'Ai', 'Female', '1988-09-09', 'Fukuoka Prefecture, Japan', 'Mausu Promotion'),
('Terui', 'Haruka', 'Female', '1987-06-07', 'Iwate Prefecture, Japan', 'Aoni Production'),
('Mizuno', 'Megumi', 'Female', '1995-03-06', 'Kanagawa Prefecture, Japan', 'Aoni Production'),
('Fujii', 'Karen', 'Female', '1996-06-15', 'Tokyo, Japan', 'LDH Japan'),
('Sakuragi', 'Tomo', 'Female', '1981-12-20', 'Kanagawa Prefecture, Japan', 'Haikyō'),
('Minase', 'Inori', 'Female', '1995-12-02', 'Tokyo, Japan', 'Axl One'),
('Inoue', 'Kenshō', 'Male', '1989-03-20', 'Kanagawa Prefecture, Japan', 'Kenchiku'),
('Kobayashi', 'Yū', 'Female', '1982-02-05', 'Tokyo, Japan', 'Holy Peak'),
('Taniyama', 'Kishō', 'Male', '1975-08-11', 'Ube, Yamaguchi Prefecture, Japan', 'INTENTION'),
('Yuuki', 'Aoi', 'Female', '1992-03-27', 'Chiba Prefecture, Japan', 'Aoni Production'),
('Tsuda', 'Kenjirō', 'Male', '1971-06-11', 'Osaka Prefecture, Japan', 'Amuleto'),
('Inoue', 'Marina', 'Female', '1985-01-20', 'Tokyo, Japan', 'Aoni Production'),
('Asano', 'Naoya', 'Male', '1977-11-01', 'Kanagawa Prefecture, Japan', 'Arts Vision'),
('Miyake', 'Kenta', 'Male', '1977-08-23', 'Okinawa, Japan', '81 Produce'),
('Hino', 'Satoshi', 'Male', '1978-08-04', 'Tokyo, Japan', 'Axl One'),
('Kobayashi', 'Chikahiro', 'Male', '1983-09-05', 'Aichi Prefecture, Japan', 'Enkikaku'),
('Senbongi', 'Sayaka', 'Female', '1995-11-24', 'Saitama Prefecture, Japan', 'I’m Enterprise'),
('Ono', 'Yūki', 'Male', '1984-06-22', 'Shizuoka Prefecture, Japan', 'Atomic Monkey'),
('Kamikawa', 'Takahiro', 'Male', '1970-07-07', 'Hokkaido, Japan', 'Office Osawa'),
('Saito', 'Atsumi', 'Female', '1993-09-30', 'Tokyo, Japan', 'Haikyō'),
('Umehara', 'Yuuichirou', 'Male', '1991-03-08', 'Osaka Prefecture, Japan', 'Arts Vision'),
('Kondo', 'Takuya', 'Male', '1978-06-05', 'Aichi Prefecture, Japan', 'Aoni Production'),
('Kuno', 'Misaki', 'Female', '1989-01-19', 'Wakayama Prefecture, Japan', 'C&O Management'),
('Shoya', 'Ishige', 'Male', '1989-05-18', 'Tochigi Prefecture, Japan', 'Pro-Fit (formerly) / Stardust Promotion'),
('Suguta', 'Hina', 'Female', '1995-12-31', 'Saitama Prefecture, Japan', 'Stardust Promotion'),
('Hara', 'Atsumi', 'Female', '1994-02-06', 'Kanagawa Prefecture, Japan', 'Art Vision'),
('Tanaka', 'Hina', 'Female', '1997-12-24', 'Aichi Prefecture, Japan', 'Mausu Promotion'),
('Amano', 'Yurina', 'Female', '1997-12-17', 'Saitama Prefecture, Japan', 'Office Osawa'),
('Mizuno', 'Risa', 'Female', '1994-03-10', 'Tokyo, Japan', 'Aoni Production'),
('Kazama', 'Yūto', 'Male', '1991-06-22', 'Chiba Prefecture, Japan', 'Haikyō'),
('Kuji', 'Rie', 'Female', '1981-01-26', 'Tokyo, Japan', 'Ken Production'),
('Yuzuki', 'Ryōta', 'Male', '1973-12-10', 'Tokyo, Japan', '81 Produce'),
('Mizuki', 'Nana', 'Female', '1980-01-21', 'Niihama, Ehime Prefecture, Japan', 'StarCrew'),
('Toyoguchi', 'Megumi', 'Female', '1978-05-02', 'Tokyo, Japan', '81 Produce'),
('Okawa', 'Toru', 'Male', '1960-02-28', 'Kagoshima Prefecture, Japan', 'Mausu Promotion'),
('Saiga', 'Mitsuaki', 'Male', '1973-09-13', 'Kanagawa Prefecture, Japan', 'Aoni Production'),
('Matsuyama', 'Takayuki', 'Male', '1970-09-18', 'Aichi Prefecture, Japan', 'Haikyō'),
('Senda', 'Mitsutaka', 'Male', '1970-11-11', 'Kanagawa Prefecture, Japan', 'Aoni Production'),
('Inoue', 'Kikuko', 'Female', '1964-09-25', 'Kanagawa Prefecture, Japan', 'Office Anemone'),
('Tokumoto', 'Yoshino', 'Female', '1968-08-13', 'Kanagawa Prefecture, Japan', '81 Produce'),
('Takahashi', 'Mikako', 'Female', '1980-05-29', 'Chiba Prefecture, Japan', 'Haikyō'),
('Itou', 'Setsuo', 'Male', '1991-03-18', 'Aichi Prefecture, Japan', 'Air Agency'),
('Ootsuka', 'Akio', 'Male', '1959-11-24', 'Tokyo, Japan', 'Mausu Promotion'),
('Sato', 'Rumi', 'Female', '1988-03-21', 'Chiba Prefecture, Japan', 'Haikyō'),
('Yoshino', 'Yūki', 'Male', '1982-02-06', 'Shizuoka Prefecture, Japan', 'Ken Production'),
('Abe', 'Atsushi', 'Male', '1981-03-25', 'Aichi Prefecture, Japan', 'Ken Production'),
('Takagi', 'Motoki', 'Male', '1986-10-05', 'Saitama Prefecture, Japan', 'Haikyō'),
('Hiroaki', 'Hirata', 'Male', '1963-12-07', 'Tokyo, Japan', 'Hirata Production'),
('Ohkawa', 'Toru', 'Male', '1960-02-28', 'Kagoshima Prefecture, Japan', 'Mausu Promotion'),
('Asano', 'Daisuke', 'Male', '1976-05-18', 'Tokyo, Japan', 'Office Osawa'),
('Kitamura', 'Eri', 'Female', '1987-08-16', 'Tokyo, Japan', 'Haikyō'),
('Nomura', 'Kenji', 'Male', '1970-07-23', 'Kumamoto Prefecture, Japan', 'Haikyō'),
('Shimamoto', 'Sumi', 'Female', '1958-12-08', 'Kumamoto Prefecture, Japan', 'Seinenza Theatre Company'),
('Matsuoka', 'Takahiro', 'Male', '1977-09-08', 'Tokyo, Japan', 'Aoni Production'),
('Kawasumi', 'Ayako', 'Female', '1976-03-30', 'Tokyo, Japan', 'Production Baobab'),
('Saito', 'Chiwa', 'Female', '1981-03-12', 'Saitama Prefecture, Japan', 'Aoni Production'),
('Seki', 'Tomokazu', 'Male', '1972-09-08', 'Tokyo, Japan', 'Atomic Monkey'),
('Nomura', 'Kengo', 'Male', '1978-04-28', 'Hyogo Prefecture, Japan', 'Mausu Promotion'),
('Mizuhashi', 'Kaori', 'Female', '1978-08-28', 'Tokyo, Japan', 'Arts Vision'),
('Toriumi', 'Kousuke', 'Male', '1973-05-16', 'Kanagawa Prefecture, Japan', 'Arts Vision'),
('Tsuda', 'Kenjirou', 'Male', '1971-06-11', 'Osaka Prefecture, Japan', 'Amuleto'),
('Shimazaki', 'Nobunaga', 'Male', '1988-12-06', 'Miyagi Prefecture, Japan', 'Aoni Production'),
('Terashima', 'Takahiro', 'Male', '1983-12-20', 'Ibaraki Prefecture, Japan', 'Haikyō'),
('Ogata', 'Kenichi', 'Male', '1942-03-29', 'Tokyo, Japan', 'Production Baobab'),
('Sawashiro', 'Miyuki', 'Female', '1985-06-02', 'Tokyo, Japan', 'I''m Enterprise'),
('Taneda', 'Risa', 'Female', '1988-07-12', 'Tokyo, Japan', 'Office Osawa'),
('Kayano', 'Ai', 'Female', '1987-09-13', 'Tokyo, Japan', 'Office Osawa'),
('Osaka', 'Ryota', 'Male', '1986-08-02', 'Tokyo, Japan', 'Early Wing'),
('Yuki', 'Aoi', 'Female', '1992-03-27', 'Chiba Prefecture, Japan', 'Aoni Production'),
('Kobayashi', 'Yūsuke', 'Male', '1985-03-25', 'Chiba Prefecture, Japan', 'Mausu Promotion'),
('Ohara', 'Sayaka', 'Female', '1975-12-06', 'Kanagawa Prefecture, Japan', 'Haikyō'),
('Kanemoto', 'Hisako', 'Female', '1987-12-16', 'Okayama Prefecture, Japan', 'Production Baobab'),
('Kaneko', 'Hikaru', 'Male', '1987-11-10', 'Tokyo, Japan', 'Arts Vision'),
('Takahashi', 'Rie', 'Female', '1994-02-27', 'Saitama Prefecture, Japan', '81 Produce'),
('Murakawa', 'Rie', 'Female', '1990-06-01', 'Aichi Prefecture, Japan', 'Haikyō'),
('Uchiyama', 'Yumi', 'Female', '1987-10-30', 'Tokyo, Japan', 'Office Osawa'),
('Arai', 'Satomi', 'Female', '1980-07-04', 'Saitama Prefecture, Japan', '81 Produce'),
('Koyasu', 'Takehito', 'Male', '1967-05-05', 'Kanagawa Prefecture, Japan', 'Toy''s Factory'),
('Akeno', 'Wakana', 'Female', '1994-01-26', 'Tokyo, Japan', 'I''m Enterprise'),
('Sakai', 'Kuran', 'Male', '1990-01-25', 'Tokyo, Japan', 'Stay-Luck'),
('Takahashi', 'Yoshitsugu', 'Male', '1986-02-07', 'Saitama Prefecture, Japan', 'I''m Enterprise'),
('Terasaki', 'Yuka', 'Female', '1987-08-29', 'Kagoshima Prefecture, Japan', 'Ogipro the Next'),
('Fukuhara', 'Ayaka', 'Female', '1988-12-31', 'Kagoshima Prefecture, Japan', '81 Produce'),
('Uemura', 'Yūto', 'Male', '1993-10-23', 'Saitama Prefecture, Japan', 'Arts Vision'),
('Kajita', 'Miyu', 'Female', '1995-10-09', 'Tokyo, Japan', 'Aoni Production'),
('Asanuma', 'Shintarō', 'Male', '1976-01-05', 'Iwate Prefecture, Japan', 'Dogwood'),
('Toyokawa', 'Atsushi', 'Male', '1979-08-17', 'Hyogo Prefecture, Japan', 'Across Entertainment'),
('Sakuragi', 'Shunsuke', 'Male', '1994-10-23', 'Aichi Prefecture, Japan', 'Atomic Monkey'),
('Nojima', 'Kenji', 'Male', '1976-03-16', 'Tokyo, Japan', 'Arts Vision'),
('Yanagita', 'Junya', 'Male', '1974-06-01', 'Tokyo, Japan', 'Haikyō'),
('Horie', 'Kazuma', 'Male', '1976-07-23', 'Osaka Prefecture, Japan', 'Production Baobab'),
('Yoshino', 'Hiroyuki', 'Male', '1970-02-06', 'Chiba Prefecture, Japan', 'Production Baobab'),
('Nojima', 'Hirofumi', 'Male', '1973-04-06', 'Tokyo, Japan', 'Arts Vision'),
('Koyama', 'Mami', 'Female', '1958-01-17', 'Tokyo, Japan', 'Aoni Production'),
('Momonga', 'Yuka', 'Female', '1981-08-02', 'Fukuoka Prefecture, Japan', 'Aoni Production'),
('Watanabe', 'Ayumu', 'Male', '1982-09-13', 'Tokyo, Japan', 'Office Osawa'),
('Matsumoto', 'Yūko', 'Female', '1983-06-11', 'Kanagawa Prefecture, Japan', 'Haikyō'),
('Momoiro', 'Yuki', 'Female', '1989-03-23', 'Tokyo, Japan', 'Ken Production'),
('Nagai', 'Takumi', 'Male', '1991-03-24', 'Kanagawa Prefecture, Japan', 'Across Entertainment'),
('Kozakura', 'Ayane', 'Female', '1993-05-28', 'Tokyo, Japan', 'Ken Production'),
('Fukushima', 'Kenji', 'Male', '1971-08-26', 'Tokyo, Japan', 'Haikyō'),
('Ohara', 'Masashi', 'Male', '1961-05-04', 'Kyoto, Japan', 'Mausu Promotion'),
('Inoue', 'Rica', 'Female', '1969-01-20', 'Tokyo, Japan', 'Ken Production'),
('Ootsuka', 'Chikao', 'Male', '1959-11-24', 'Tokyo, Japan', 'Mausu Promotion'),
('Sato', 'Tomokazu', 'Male', '1970-06-11', 'Tokyo, Japan', 'Haikyō'),
('Kurita', 'Kaori', 'Female', '1977-02-03', 'Tokyo, Japan', '81 Produce'),
('Ooshima', 'Takashi', 'Male', '1966-07-07', 'Tokyo, Japan', 'Production Baobab'),
('Yamaguchi', 'Keiko', 'Female', '1974-02-22', 'Tokyo, Japan', 'Haikyō'),
('Kobayashi', 'Masakazu', 'Male', '1971-10-07', 'Tokyo, Japan', 'Haikyō'),
('Suzuki', 'Minori', 'Female', '1997-11-24', 'Hokkaido Prefecture, Japan', 'Ken Production'),
('Saiga', 'Mitsuki', 'Female', '1974-02-22', 'Kanagawa Prefecture, Japan', 'Ken Production'),
('Yashiro', 'Taku', 'Male', '1995-05-06', 'Chiba Prefecture, Japan', '81 Produce'),
('Shindō', 'Kei', 'Female', '1983-09-10', 'Chiba Prefecture, Japan', 'Axlone'),
('Nagashima', 'Wasabi', 'Male', '1960-12-18', 'Tokyo, Japan', 'Aoni Production'),
('Tsunoda', 'Kaneto', 'Male', '1941-10-28', 'Tokyo, Japan', 'Production Baobab'),
('Kobayashi', 'Masako', 'Female', '1936-11-25', 'Tokyo, Japan', 'Production Baobab'),
('Fukuen', 'Mika', 'Female', '1965-10-29', 'Tokyo, Japan', 'Ken Production'),
('Miyamoto', 'Mitsuko', 'Female', '1947-07-18', 'Tokyo, Japan', 'Production Baobab'),
('Shinohara', 'Emi', 'Female', '1963-11-22', 'Tokyo, Japan', 'Production Baobab'),
('Fukuhara', 'Kaori', 'Female', '1981-07-29', 'Tokyo, Japan', '81 Produce'),
('Horie', 'Yui', 'Female', '1987-09-05', 'Tokyo, Japan', 'Arts Vision'),
('Katou', 'Keiko', 'Female', '1969-02-06', 'Tokyo, Japan', 'Production Baobab'),
('Kawanishi', 'Kenn', 'Male', '1965-02-14', 'Tokyo, Japan', 'Aoni Production'),
('Fukuhara', 'Maaya', 'Female', '1983-03-06', 'Tokyo, Japan', '81 Produce'),
('Furuya', 'Toshio', 'Male', '1960-11-18', 'Tokyo, Japan', 'Haikyō'),
('Matsuzaka', 'Rumi', 'Female', '1961-01-30', 'Tokyo, Japan', 'Production Baobab'),
('Ichimichi', 'Mikako', 'Female', '1996-10-26', 'Tokyo, Japan', 'Haikyō'),
('Okamoto', 'Takahiro', 'Male', '1963-10-05', 'Tokyo, Japan', 'Aoni Production'),
('Shiozawa', 'Kaneto', 'Male', '1954-01-28', 'Tokyo, Japan', 'Aoni Production'),
('Tateno', 'Noriko', 'Female', '1951-04-14', 'Tokyo, Japan', 'Ken Production'),
('Toda', 'Keiko', 'Female', '1957-09-18', 'Aichi, Japan', 'Talent Office T''s'),
('Taguchi', 'Yoshiko', 'Female', '1944-09-22', 'Tokyo, Japan', 'Aoni Production'),
('Mizuno', 'Kenji', 'Male', '1934-08-10', 'Japan', 'Self-Employed'),
('Takashima', 'Gara', 'Female', '1954-01-25', 'Tokyo, Japan', 'Theatre Echo'),
('Kida', 'Saburou', 'Male', '1942-05-02', 'Tokyo, Japan', 'Production Baobab'),
('Ikeda', 'Masako', 'Female', '1939-01-01', 'Tokyo, Japan', 'Haikyō'),
('Mizushima', 'Yū', 'Male', '1953-06-18', 'Tokyo, Japan', 'Ken Production'),
('Yamadera', 'Kōichi', 'Male', '1961-06-17', 'Shiogama, Miyagi, Japan', 'Across Entertainment'),
('Tada', 'Aoi', 'Female', '1981-07-03', 'Tokyo, Japan', 'Himawari Theatre Group'),
('Naya', 'Gorō', 'Male', '1929-11-17', 'Hakodate, Hokkaidō, Japan', 'Theatre Echo'),
('Iwata', 'Mitsuo', 'Male', '1967-07-31', 'Saitama, Japan', 'Aoni Production'),
('Tsuru', 'Hiromi', 'Female', '1960-03-29', 'Kanagawa, Japan', 'Aoni Production'),
('Kikuchi', 'Masami', 'Male', '1960-10-24', 'Nagano, Japan', 'Ken Production'),
('Takada', 'Yumi', 'Female', '1961-09-21', 'Tokyo, Japan', 'Aoni Production'),
('Yokoyama', 'Chisa', 'Female', '1966-12-20', 'Tokyo, Japan', 'Aksent'),
('Mizutani', 'Yūko', 'Female', '1964-11-04', 'Aichi, Japan', 'Aoni Production'),
('Tomizawa', 'Michie', 'Female', '1960-10-20', 'Nagano, Japan', 'Aoni Production'),
('Kobayashi', 'Yūko', 'Female', '1959-02-06', 'Tokyo, Japan', 'Aoni Production'),
('Kozakura', 'Etsuko', 'Female', '1971-02-22', 'Tokyo, Japan', '81 Produce'),
('Hirohashi', 'Ryō', 'Female', '1977-08-05', 'Mitsuke, Niigata, Japan', 'Aoni Production'),
('Noto', 'Mamiko', 'Female', '1980-02-06', 'Kanazawa, Ishikawa, Japan', 'Office Osawa'),
('Nonaka', 'Ai', 'Female', '1981-06-08', 'Sawara-ku, Fukuoka, Japan', 'Aoni Production'),
('Okiayu', 'Ryōtarō', 'Male', '1969-11-17', 'Kitakyushu, Fukuoka, Japan', 'Aoni Production'),
('Kobayashi', 'Sanae', 'Female', '1980-01-26', 'Hamakita, Shizuoka, Japan', 'Sigma Seven'),
('Suzuki', 'Chihiro', 'Male', '1977-02-17', 'Yamagata Prefecture, Japan', 'Haikyou'),
('Gibu', 'Yūko', 'Female', '1981-01-28', 'Kōbe, Hyōgo, Japan', 'Freelance'),
('Kiuchi', 'Hidenobu', 'Male', '1969-02-05', 'Kobe, Hyōgo Prefecture, Japan', 'Office Osawa'),
('Kawakami', 'Tomoko', 'Female', '1970-04-25', 'Tokyo, Japan', 'Production Baobab'),
('Fuchizaki', 'Yuriko', 'Female', '1968-12-05', 'Ōta, Tokyo, Japan', 'REMAX'),
('Kosugi', 'Jūrōta', 'Male', '1957-12-19', 'Kanagawa Prefecture, Japan', 'Office Osawa'),
('Hisakawa', 'Aya', 'Female', '1968-11-12', 'Kaizuka, Osaka Prefecture, Japan', 'Aoni Production'),
('Shiratori', 'Yuri', 'Female', '1968-08-20', 'Kanagawa Prefecture, Japan', 'Arts Vision');