CREATE DATABASE IF NOT EXISTS anime_db;
USE anime_db;

DROP TABLE IF EXISTS series;

CREATE TABLE series (
	series_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    genre VARCHAR(100) NOT NULL,
    release_year INT,
    total_episode_count INT,
    status_of_series VARCHAR(10)
);

INSERT INTO series (title, genre, release_year, total_episode_count, status_of_series)
VALUES

('Hunter x Hunter', 'Action, Adventure, Fantasy', '2011', '148', 'Complete'),
('Death Note', 'Supernatural, Suspense', '2006', '37', 'Complete'),
('One Punch Man', 'Action, Comedy', '2015', '12', 'Complete'),
('One Punch Man Second Season', 'Action, Comedy', '2019', '12', 'Complete'),
('One Punch Man 3', 'Action, Comedy', '2025', '4', 'On-Going'),
('Demon Slayer: Kimetsu no Yaiba', 'Action, Supernatural, Award Winning', '2019', '26', 'Complete'),
('Demon Slayer: Kimetsu no Yaiba Mugen Train Arc', 'Action, Supernatural', '2021', '7', 'Complete'),
('Demon Slayer: Kimetsu no Yaiba Entertainment District Arc', 'Action, Supernatural', '2021', '11', 'Complete'),
('Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc', 'Action, Supernatural', '2023', '11', 'Complete'),
('Demon Slayer: Kimetsu no Yaiba Hashira Training Arc', 'Action, Supernatural', '2024', '8', 'Complete'),
('Ouran High School Host Club', 'Comedy, Romance', '2006', '26', 'Complete'),
('JoJo’s Bizarre Adventure', 'Action, Adventure, Drama', '2012', '26', 'Complete'),
('JoJo’s Bizarre Adventure Season 2', 'Action, Adventure, Drama', '2014', '48', 'Complete'),
('JoJo’s Bizarre Adventure Season 3', 'Action, Adventure, Drama', '2016', '39', 'Complete'),
('JoJo’s Bizarre Adventure Season 4', 'Action, Adventure, Drama', '2018', '39', 'Complete'),
('JoJo’s Bizarre Adventure Season 5', 'Action, Adventure, Drama', '2021', '38', 'Complete'),
('Haikyuu!!', 'Sports', '2014', '25', 'Complete'),
('Haikyuu!! Second Season', 'Sports', '2015', '25', 'Complete'),
('Haikyuu!! Karasuno Koukou vs Shiratorizawa Gakuen Koukou', 'Sports', '2016', '10', 'Complete'),
('Haikyuu!! To The Top', 'Sports', '2020', '25', 'Complete'),
('My Hero Academia', 'Action', '2016', '13', 'Complete'),
('My Hero Academia Season 2', 'Action', '2017', '25', 'Complete'),
('My Hero Academia Season 3', 'Action', '2018', '25', 'Complete'),
('My Hero Academia Season 4', 'Action', '2019', '25', 'Complete'),
('My Hero Academia Season 5', 'Action', '2021', '25', 'Complete'),
('My Hero Academia Season 6', 'Action', '2022', '25', 'Complete'),
('My Hero Academia Season 7', 'Action', '2024', '21', 'Complete'),
('My Hero Academia Season 8', 'Action', '2025', '6', 'On-Going'),
('Spy x Family', 'Action, Award Winning, Comedy', '2022', '25', 'Complete'),
('Spy x Family Season 2', 'Action, Comedy', '2023', '12', 'Complete'),
('Spy x Family Season 3', 'Action, Comedy', '2025', '13', 'On-Going'),
('Naruto', 'Action, Adventure, Fantasy', '2002', '220', 'Complete'),
('Naruto: Shippuden', 'Action, Adventure, Fantasy', '2007', '500', 'Complete'),
('One Piece', 'Action, Adventure, Fantasy', '1999', '1148', 'On-Going'),
('Bleach', 'Action, Adventure, Fantasy', '2004', '366', 'Complete'),
('Bleach: Thousand-Year Blood War', 'Action, Adventure, Supernatural', '2022', '13', 'Complete'),
('Bleach: Thousand-Year Blood War - The Separation', 'Action, Adventure, Supernatural', '2023', '13', 'Complete'),
('Bleach: Thousand-Year Blood War - The Conflict', 'Action, Adventure, Supernatural', '2024', '14', 'Complete'),
('GACHIAKUTA', 'Action, Fantasy', '2025', '24', 'On-Going'),
('Tougen Anki: Dark Demon of Paradise', 'Action, Fantasy', '2025', '15', 'On-Going'),
('Jujutsu Kaisen', 'Action, Award Winning, Supernatural', '2020', '24', 'Complete'),
('Jujutsu Kaisen Season 2', 'Action, Supernatural', '2023', '23', 'Complete'),
('Tokyo Revengers', 'Action, Drama', '2021', '24', 'Complete'),
('Tokyo Revengers: Christmas Showdown', 'Action, Drama', '2023', '13', 'Complete'),
('Tokyo Revengers: Tenjiku Arc', 'Action, Drama', '2023', '13', 'Complete'),
('Banana Fish', 'Action, Adventure, Drama, Suspense', '2018', '24', 'Complete'),
('Dragon Ball Z', 'Action, Adventure, Comedy, Fantasy', '1989', '291', 'Complete'),
('The Apothecary Diaries', 'Drama, Mystery', '2023', '24', 'Complete'),
('The Apothecary Diaries Season 2', 'Drama, Mystery', '2025', '24', 'Complete'),
('Kaguya-sama: Love Is War', 'Comedy, Romance', '2019', '12', 'Complete'),
('Kaguya-sama wa Kokurasetai? Tensai-tachi no Renai Zunousen', 'Comedy, Romance', '2020', '12', 'Complete'),
('Kaguya-sama wa Kokurasetai: Ultra Romantic', 'Comedy, Romance', '2022', '13', 'Complete'),
('Violet Evergarden', 'Drama', '2018', '13', 'Complete'),
('Attack on Titan', 'Action, Award Winning, Drama, Suspense', '2013', '25', 'Complete'),
('Attack on Titan Season 2', 'Action, Award Winning, Drama, Suspense', '2017', '12', 'Complete'),
('Attack on Titan Season 3', 'Action, Drama, Suspense', '2018', '22', 'Complete'),
('Attack on Titan Season 4', 'Action, Drama, Suspense', '2020', '30', 'Complete'),
('Beastars', 'Drama, Suspense', '2019', '12', 'Complete'),
('Beastars Season 2', 'Drama, Suspense', '2021', '12', 'Complete'),
('Beastars Season 3', 'Drama, Suspense', '2024', '12', 'Complete'),
('My Dress-Up Darling', 'Romance', '2022', '12', 'Complete'),
('My Dress-Up Darling Season 2', 'Romance', '2025', '12', 'Complete'),
('Fullmetal Alchemist', 'Action, Adventure, Award Winning, Drama, Fantasy', '2003', '51', 'Complete'),
('Fullmetal Alchemist: Brotherhood', 'Action, Adventure, Drama, Fantasy', '2009', '64', 'Complete'),
('Mob Psycho 100', 'Action, Comedy, Supernatural', '2016', '12', 'Complete'),
('Mob Psycho 100 Season 2', 'Action, Comedy, Supernatural', '2019', '13', 'Complete'),
('Mob Psycho 100 Season 3', 'Action, Comedy, Supernatural', '2022', '12', 'Complete'),
('Black Lagoon', 'Action', '2006', '12', 'Complete'),
('Black Lagoon: The Second Barrage', 'Action', '2006', '12', 'Complete'),
('Fate/Zero', 'Action, Fantasy', '2011', '13', 'Complete'),
('Fate/Zero Season 2', 'Action, Fantasy', '2012', '12', 'Complete'),
('Fruits Basket', 'Drama, Romance, Supernatural', '2019', '25', 'Complete'),
('Fruits Basket Season 2', 'Drama, Romance, Supernatural', '2020', '25', 'Complete'),
('Fruits Basket Season 3', 'Drama, Romance, Supernatural', '2021', '13', 'Complete'),
('Your Lie in April', 'Drama, Romance', '2014', '22', 'Complete'),
('Re: Zero - Starting Life in Another World', 'Drama, Fantasy, Suspense', '2016', '25', 'Complete'),
('Re: Zero - Starting Life in Another World Season 2', 'Drama, Fantasy, Suspense', '2020', '13', 'Complete'),
('Bungo Stray Dogs', 'Action, Mystery', '2016', '12', 'Complete'),
('Bungo Stray Dogs Season 2', 'Action, Mystery', '2016', '12', 'Complete'),
('Bungo Stray Dogs Season 3', 'Action, Mystery', '2019', '12', 'Complete'),
('Bungo Stray Dogs Season 4', 'Action, Mystery', '2023', '13', 'Complete'),
('Bungo Stray Dogs Season 5', 'Action, Mystery', '2023', '11', 'Complete'),
('Yuri!!! On Ice', 'Award Winning, Sports', '2016', '12', 'Complete'),
('No Game, No Life', 'Comedy, Fantasy, Ecchi', '2014', '12', 'Complete'),
('Orange', 'Drama, Romance, Sci-Fi', '2016', '13', 'Complete'),
('The Rising of the Shield Hero', 'Action, Adventure, Drama, Fantasy', '2019', '25', 'Complete'),
('The Rising of the Shield Hero Season 2', 'Action, Adventure, Drama, Fantasy', '2022', '13', 'Complete'),
('The Rising of the Shield Hero Season 3', 'Action, Adventure, Drama, Fantasy', '2023', '12', 'Complete'),
('The Rising of the Shield Hero Season 4', 'Action, Adventure, Drama, Fantasy', '2025', '12', 'Complete'),
('Tower of God', 'Action, Adventure, Drama, Fantasy, Mystery', '2020', '13', 'Complete'),
('Tower of God Season 2: Return of the Prince', 'Action, Adventure, Drama, Fantasy, Mystery', '2024', '13', 'Complete'),
('Tower of God Season 2: Workshop Battle', 'Action, Adventure, Drama, Fantasy, Mystery', '2024', '13', 'Complete'),
('Food Wars: Shokugeki no Soma', 'Gourmet, Ecchi', '2015', '24', 'Complete'),
('Food Wars! The Second Plate', 'Gourmet, Ecchi', '2016', '13', 'Complete'),
('Food Wars! The Third Plate', 'Gourmet, Ecchi', '2017', '12', 'Complete'),
('Food Wars! The Third Plate: Totsuki Train Arc', 'Gourmet, Ecchi', '2018', '12', 'Complete'),
('Food Wars! The Fourth Plate', 'Gourmet, Ecchi', '2019', '12', 'Complete'),
('Food Wars! The Fifth Plate', 'Gourmet, Ecchi', '2020', '13', 'Complete'),
('Slam Dunk', 'Sports', '1993', '101', 'Complete'),
('Pokémon', 'Action, Adventure, Comedy, Fantasy', '1997', '276', 'Complete'),
('Pokémon: Advanced', 'Action, Adventure, Comedy, Fantasy', '2002', '192', 'Complete'),
('Pokémon: Diamond and Pearl', 'Action, Adventure, Comedy, Fantasy', '2006', '191', 'Complete'),
('Pokémon: Black & White', 'Action, Adventure, Comedy, Fantasy', '2010', '84', 'Complete'),
('Pokémon: Black & White: Rival Destinies', 'Action, Adventure, Comedy, Fantasy', '2012', '24', 'Complete'),
('Pokémon: Black & White: Adventures in Unova', 'Action, Adventure, Comedy, Fantasy', '2013', '14', 'Complete'),
('Pokémon: Black & White: Adventures in Unova and Beyond', 'Action, Adventure, Comedy, Fantasy', '2013', '20', 'Complete'),
('Pokémon the Series: XY', 'Action, Adventure, Comedy, Fantasy', '2013', '93', 'Complete'),
('Pokémon the Series: XYZ', 'Action, Adventure, Comedy, Fantasy', '2015', '47', 'Complete'),
('Pokémon the Series: Sun & Moon', 'Action, Fantasy', '2016', '146', 'Complete'),
('Pokémon Journeys: The Series', 'Action, Adventure, Comedy, Fantasy', '2019', '136', 'Complete'),
('Pokémon: To Be a Pokémon Master', 'Action, Adventure, Comedy, Fantasy', '2023', '11', 'Complete'),
('Doraemon', 'Adventure, Comedy, Fantasy, Sci-Fi', '1979', '1787', 'Complete'),
('Digimon Adventures', 'Action, Adventure, Comedy, Fantasy', '1999', '54', 'Complete'),
('Sailor Moon', 'Romance', '1992', '46', 'Complete'),
('Sailor Moon R', 'Romance', '1993', '43', 'Complete'),
('Sailor Moon S', 'Romance', '1994', '38', 'Complete'),
('Sailor Moon SuperS', 'Romance', '1995', '39', 'Complete'),
('Sailor Moon Sailor Stars', 'Romance', '1996', '34', 'Complete'),
('Nana', 'Drama, Romance', '2006', '47', 'Complete'),
('Paradise Kiss', 'Drama, Romance', '2005', '12', 'Complete'),
('Tokyo Ghoul', 'Action, Fantasy, Horror, Suspense', '2014', '12', 'Complete'),
('Tokyo Ghoul √A', 'Gore, Psychological, Urban Fantasy', '2015', '12', 'Complete'),
('Tokyo Ghoul:re', 'Gore, Psychological, Urban Fantasy', '2018', '12', 'Complete'),
('Tokyo Ghoul:re 2nd Season', 'Gore, Psychological, Urban Fantasy', '2018', '12', 'Complete'),
('Sword Art Online', 'Action, Adventure, Fantasy, Romance', '2012', '25', 'Complete'),
('Sword Art Online II', 'Action, Adventure, Fantasy, Romance', '2014', '24', 'Complete'),
('Sword Art Online: Alicization', 'Action, Adventure, Fantasy', '2018', '24', 'Complete'),
('Sword Art Online: Alicization - War of Underworld', 'Action, Adventure, Fantasy', '2019', '12', 'Complete'),
('Sword Art Online: Alicization - War of Underworld Part 2', 'Action, Adventure, Fantasy', '2020', '11', 'Complete'),
('Psycho-Pass', 'Action, Mystery, Sci-Fi, Suspense', '2012', '22', 'Complete'),
('Psycho-Pass 2', 'Action, Mystery, Sci-Fi, Suspense', '2014', '11', 'Complete'),
('Psycho-Pass 3', 'Action, Mystery, Sci-Fi, Suspense', '2019', '8', 'Complete'),
('Neon Genesis Evangelion', 'Avant Garde, Award Winning, Drama, Sci-Fi, Suspense', '1995', '26', 'Complete'),
('Toradora!', 'Drama, Romance', '2008', '25', 'Complete'),
('Danganronpa: The Animation', 'Horror, Mystery, Suspense', '2013', '13', 'Complete'),
('Danganronpa 3: The End of Hopes Peak High School - Despair Arc', 'Action, Horror, Mystery, Suspense', '2016', '11', 'Complete'),
('Danganronpa 3: The End of Hopes Peak High School - Future Arc', 'Action, Horror, Mystery, Suspense', '2016', '12', 'Complete'),
('Given', 'Boys Love, Drama', '2019', '11', 'Complete'),
('Bloom Into You', 'Drama, Girls Love', '2018', '13', 'Complete'),
('Gintama', 'Action, Comedy, Sci-Fi', '2006', '201', 'Complete'),
('Gintama Season 2', 'Action, Comedy, Sci-Fi', '2011', '51', 'Complete'),
('Gintama: Enchousen', 'Action, Comedy, Sci-Fi', '2012', '13', 'Complete'),
('Gintama Season 4', 'Action, Comedy, Sci-Fi', '2015', '51', 'Complete'),
('Gintama Season 5', 'Action, Comedy, Sci-Fi', '2017', '12', 'Complete'),
('Gintama. Slip Arc', 'Action, Comedy, Sci-Fi', '2017', '13', 'Complete'),
('Gintama. Silver Soul Arc', 'Action, Comedy, Sci-Fi', '2018', '12', 'Complete'),
('Gintama. Silver Soul Arc - Second Half War', 'Action, Comedy, Sci-Fi', '2018', '14', 'Complete'),
('High School DxD', 'Action, Comedy, Romance, Supernatural, Ecchi', '2018', '12', 'Complete'),
('Berserk', 'Action, Adventure, Drama, Fantasy, Horror', '1997', '25', 'Complete'),
('Berserk (2016)', 'Action, Adventure, Drama, Fantasy, Horror', '2016', '12', 'Complete'),
('Berserk: Season II', 'Gore, Military, Psychological', '2017', '12', 'Complete'),
('Carole And Tuesday', 'Drama, Sci-Fi', '2019', '24', 'Complete'),
('Rose Of Versailles', 'Drama, Romance', '1979', '40', 'Complete'),
('Cowboy Bebop', 'Action, Award Winning, Sci-Fi', '1998', '26', 'Complete'),
('Golden Kamuy', 'Action, Adventure', '2018', '12', 'Complete'),
('Golden Kamuy Season 2', 'Action, Adventure', '2018', '12', 'Complete'),
('Golden Kamuy Season 3', 'Action, Adventure', '2020', '12', 'Complete'),
('Golden Kamuy Season 4', 'Action, Adventure', '2022', '13', 'Complete'),
('Tenchi Muyou!', 'Comedy, Romance, Sci-Fi', '1995', '26', 'Complete'),
('Castlevania', 'Fantasy, Horror, Action, Adventure', '2017', '32', 'Complete'),
('Clannad', 'Drama, Romance', '2007', '23', 'Complete'),
('Clannad: After Story', 'Drama, Romance', '2008', '24', 'Complete'),
('Elfen Lied', 'Action, Drama, Horror, Romance, Suspense', '2004', '13', 'Complete'),
('Monster', 'Drama, Mystery, Suspense', '2004', '74', 'Complete'),
('Revolutionary Girl Utena', 'Drama, Award Winning', '1997', '39', 'Complete');
