CREATE DATABASE IF NOT EXISTS anime_db;
USE anime_db;

DROP TABLE IF EXISTS series;

CREATE TABLE series (
	series_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    genre VARCHAR(100) NOT NULL,
    release_year INT,
    total_episode_count INT,
    status_of_series VARCHAR(10)
);

INSERT INTO series (title, genre, release_year, total_episode_count, status_of_series)
VALUES

('Hunter x Hunter', 'Action, Adventure, Fantasy', '2011', '148', 'Complete'),
('Death Note', 'Supernatural, Suspense', '2006', '37', 'Complete'),
('One Punch Man', 'Action, Comedy', '2015', '12', 'Complete'),
('One Punch Man Second Season', 'Action, Comedy', '2019', '12', 'Complete'),
('One Punch Man 3', 'Action, Comedy', '2025', '4', 'On-Going'),
('Demon Slayer: Kimetsu no Yaiba', 'Action, Supernatural, Award Winning', '2019', '26', 'Complete'),
('Demon Slayer: Kimetsu no Yaiba Mugen Train Arc', 'Action, Supernatural', '2021', '7', 'Complete'),
('Demon Slayer: Kimetsu no Yaiba Entertainment District Arc', 'Action, Supernatural', '2021', '11', 'Complete'),
('Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc', 'Action, Supernatural', '2023', '11', 'Complete'),
('Demon Slayer: Kimetsu no Yaiba Hashira Training Arc', 'Action, Supernatural', '2024', '8', 'Complete'),
('Ouran High School Host Club', 'Comedy, Romance', '2006', '26', 'Complete'),
('JoJo’s Bizarre Adventure', 'Action, Adventure, Drama', '2012', '26', 'Complete'),
('JoJo’s Bizarre Adventure Season 2', 'Action, Adventure, Drama', '2014', '48', 'Complete'),
('JoJo’s Bizarre Adventure Season 3', 'Action, Adventure, Drama', '2016', '39', 'Complete'),
('JoJo’s Bizarre Adventure Season 4', 'Action, Adventure, Drama', '2018', '39', 'Complete'),
('JoJo’s Bizarre Adventure Season 5', 'Action, Adventure, Drama', '2021', '38', 'Complete'),
('Haikyuu!!', 'Sports', '2014', '25', 'Complete'),
('Haikyuu!! Second Season', 'Sports', '2015', '25', 'Complete'),
('Haikyuu!! Karasuno Koukou vs Shiratorizawa Gakuen Koukou', 'Sports', '2016', '10', 'Complete'),
('Haikyuu!! To The Top', 'Sports', '2020', '25', 'Complete'),
('My Hero Academia', 'Action', '2016', '13', 'Complete'),
('My Hero Academia Season 2', 'Action', '2017', '25', 'Complete'),
('My Hero Academia Season 3', 'Action', '2018', '25', 'Complete'),
('My Hero Academia Season 4', 'Action', '2019', '25', 'Complete'),
('My Hero Academia Season 5', 'Action', '2021', '25', 'Complete'),
('My Hero Academia Season 6', 'Action', '2022', '25', 'Complete'),
('My Hero Academia Season 7', 'Action', '2024', '21', 'Complete'),
('My Hero Academia Season 8', 'Action', '2025', '6', 'On-Going'),
('Spy x Family', 'Action, Award Winning, Comedy', '2022', '25', 'Complete'),
('Spy x Family Season 2', 'Action, Comedy', '2023', '12', 'Complete'),
('Spy x Family Season 3', 'Action, Comedy', '2025', '13', 'On-Going'),
('Naruto', 'Action, Adventure, Fantasy', '2002', '220', 'Complete'),
('Naruto: Shippuden', 'Action, Adventure, Fantasy', '2007', '500', 'Complete'),
('One Piece', 'Action, Adventure, Fantasy', '1999', '1148', 'On-Going'),
('Bleach', 'Action, Adventure, Fantasy', '2004', '366', 'Complete'),
('Bleach: Thousand-Year Blood War', 'Action, Adventure, Supernatural', '2022', '13', 'Complete'),
('Bleach: Thousand-Year Blood War - The Separation', 'Action, Adventure, Supernatural', '2023', '13', 'Complete'),
('Bleach: Thousand-Year Blood War - The Conflict', 'Action, Adventure, Supernatural', '2024', '14', 'Complete'),
('GACHIAKUTA', 'Action, Fantasy', '2025', '24', 'On-Going'),
('Tougen Anki: Dark Demon of Paradise', 'Action, Fantasy', '2025', '15', 'On-Going'),
('Jujutsu Kaisen', 'Action, Award Winning, Supernatural', '2020', '24', 'Complete'),
('Jujutsu Kaisen Season 2', 'Action, Supernatural', '2023', '23', 'Complete'),
('Tokyo Revengers', 'Action, Drama', '2021', '24', 'Complete'),
('Tokyo Revengers: Christmas Showdown', 'Action, Drama', '2023', '13', 'Complete'),
('Tokyo Revengers: Tenjiku Arc', 'Action, Drama', '2023', '13', 'Complete'),
('Banana Fish', 'Action, Adventure, Drama, Suspense', '2018', '24', 'Complete'),
('Dragon Ball Z', 'Action, Adventure, Comedy, Fantasy', '1989', '291', 'Complete'),
('The Apothecary Diaries', 'Drama, Mystery', '2023', '24', 'Complete'),
('The Apothecary Diaries Season 2', 'Drama, Mystery', '2025', '24', 'Complete'),
('Kaguya-sama: Love Is War', 'Comedy, Romance', '2019', '12', 'Complete'),
('Kaguya-sama wa Kokurasetai? Tensai-tachi no Renai Zunousen', 'Comedy, Romance', '2020', '12', 'Complete'),
('Kaguya-sama wa Kokurasetai: Ultra Romantic', 'Comedy, Romance', '2022', '13', 'Complete'),
('Violet Evergarden', 'Drama', '2018', '13', 'Complete'),
('Attack on Titan', 'Action, Award Winning, Drama, Suspense', '2013', '25', 'Complete'),
('Attack on Titan Season 2', 'Action, Award Winning, Drama, Suspense', '2017', '12', 'Complete'),
('Attack on Titan Season 3', 'Action, Drama, Suspense', '2018', '22', 'Complete'),
('Attack on Titan Season 4', 'Action, Drama, Suspense', '2020', '30', 'Complete'),
('Beastars', 'Drama, Suspense', '2019', '12', 'Complete'),
('Beastars Season 2', 'Drama, Suspense', '2021', '12', 'Complete'),
('Beastars Season 3', 'Drama, Suspense', '2024', '12', 'Complete'),
('My Dress-Up Darling', 'Romance', '2022', '12', 'Complete'),
('My Dress-Up Darling Season 2', 'Romance', '2025', '12', 'Complete'),
('Fullmetal Alchemist', 'Action, Adventure, Award Winning, Drama, Fantasy', '2003', '51', 'Complete'),
('Fullmetal Alchemist: Brotherhood', 'Action, Adventure, Drama, Fantasy', '2009', '64', 'Complete'),
('Mob Psycho 100', 'Action, Comedy, Supernatural', '2016', '12', 'Complete'),
('Mob Psycho 100 Season 2', 'Action, Comedy, Supernatural', '2019', '13', 'Complete'),
('Mob Psycho 100 Season 3', 'Action, Comedy, Supernatural', '2022', '12', 'Complete'),
('Black Lagoon', 'Action', '2006', '12', 'Complete'),
('Black Lagoon: The Second Barrage', 'Action', '2006', '12', 'Complete'),
('Fate/Zero', 'Action, Fantasy', '2011', '13', 'Complete'),
('Fate/Zero Season 2', 'Action, Fantasy', '2012', '12', 'Complete'),
('Fruits Basket', 'Drama, Romance, Supernatural', '2019', '25', 'Complete'),
('Fruits Basket Season 2', 'Drama, Romance, Supernatural', '2020', '25', 'Complete'),
('Fruits Basket Season 3', 'Drama, Romance, Supernatural', '2021', '13', 'Complete'),
('Your Lie in April', 'Drama, Romance', '2014', '22', 'Complete'),
('Re: Zero - Starting Life in Another World', 'Drama, Fantasy, Suspense', '2016', '25', 'Complete'),
('Re: Zero - Starting Life in Another World Season 2', 'Drama, Fantasy, Suspense', '2020', '13', 'Complete'),
('Bungo Stray Dogs', 'Action, Mystery', '2016', '12', 'Complete'),
('Bungo Stray Dogs Season 2', 'Action, Mystery', '2016', '12', 'Complete'),
('Bungo Stray Dogs Season 3', 'Action, Mystery', '2019', '12', 'Complete'),
('Bungo Stray Dogs Season 4', 'Action, Mystery', '2023', '13', 'Complete'),
('Bungo Stray Dogs Season 5', 'Action, Mystery', '2023', '11', 'Complete'),
('Yuri!!! On Ice', 'Award Winning, Sports', '2016', '12', 'Complete'),
('No Game, No Life', 'Comedy, Fantasy, Ecchi', '2014', '12', 'Complete'),
('Orange', 'Drama, Romance, Sci-Fi', '2016', '13', 'Complete'),
('The Rising of the Shield Hero', 'Action, Adventure, Drama, Fantasy', '2019', '25', 'Complete'),
('The Rising of the Shield Hero Season 2', 'Action, Adventure, Drama, Fantasy', '2022', '13', 'Complete'),
('The Rising of the Shield Hero Season 3', 'Action, Adventure, Drama, Fantasy', '2023', '12', 'Complete'),
('The Rising of the Shield Hero Season 4', 'Action, Adventure, Drama, Fantasy', '2025', '12', 'Complete');


